### ISSUE TITLE
如果不是HTTP2

### ISSUE THREAD

**Issue by YukiYlf** [jauntsdn/netty-websocket-http2#1]
那么SSL的pkcs12协议是否一样

**Comment by mostroverkhov** [comment]
websocket-over-Http2 handlers *should* be compatible with http1 websocket handshake handlers on same pipeline - this library only concerned about `CONNECT` requests having `:protocol` header set.

Hopefully this answers your question, otherwise I encourage you to use English as google translate is not very helpful.
